version: '2'

services:
  webserver:
    build: ./docker/webserver
    image: gmc-backend-docker
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - /home/karan/Workspace/web/gmc-ab/src:/var/www/html
    links:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./db_docker:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=db_docker
    links:
      - phpmyadmin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8500:80"
    environment:
      - MYSQL_ROOT_PASSWORD=docker